# Generated by Django 5.1.4 on 2026-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_n_air', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('received', 'Buyurtma qabul qilindi 📥'), ('assembled', "Buyurtma yig'ildi 📦"), ('shipping', "Yo'lda 🚚"), ('delivered', 'Yetkazib berildi ✅'), ('canceled', 'Bekor qilindi ❌')], default='received', max_length=20),
        ),
    ]
